Fix some issues with test, update record, and rework realtime_updates example
thijsmie/pocketbase-async pull request #6
Opened 2024-02-27 13:20 UTC by matthieuEv

### Checklist

* [ x ] I have read the Contribution Guidelines
* [ x ] I have read and agree to the Code of Conduct
* [ x ] I have read and agree that my contributions will be included under the project license
* [ x ] I have added a description of my changes and why I want them _or_ linked the relevant pull request below
* [ x ] I have ran the formatter, linter and tests locally and ensured they give their all green
* [ x ] If contributing new code: I've ensured my new code is covered sufficiently by unit and integration tests

### Description of Changes

I have reworked the `realtime_updates.py` example which was giving an error: `httpx.ConnectError: All connection attempts failed` and added an exception handling system.

I fixed a bug in `test_admin` where the function `def test_login(admin_client: PocketBase, admin: tuple[str, str])` was not in `async` and therefore returned an error when testing with pytest.

I modified the `subscribe` function in `record.py` to be more faithful to the Pocketbase documentation:

- If the `record_id` is empty, an error is returned.
- If it contains `"*"`, then the subscription is made on all records in the collection.
- If it contains a specific `record_id`, then the subscription is made on that particular record.

### Related Issues

None

2024-02-28 14:43 UTC, thijsmie requested changes
Thank you for contributing! I have one remark which I'd like you to address before I merge this.

2024-02-28 14:43 UTC, thijsmie commented on src/pocketbase/services/record.py
> +            raise ValueError("Invalid record_id: None")
I see your motivation for this change is "I modified the subscribe function in record.py to be more faithful to the Pocketbase documentation". I think that is invalid in this case: I do not like the magic "*" character meaning something in a function argument but I do think that making it value `None` is sufficient. I'd ask you to either revert this change _or_ split the subscribe function to a `subscribe` and a `subscribe_all` function or something.

2024-02-29 10:45 UTC, matthieuEv commented
I understand your point about the "*" character being non-standard and potentially confusing, especially given the stronger typing support in Python compared to Javascript.

While my initial goal was to align the function with the Pocketbase documentation, I agree that clarity and maintainability are important. Based on your suggestion, I'll split the subscribe function into two separate functions: `subscribe` (for specific record ID) and `subscribe_all` (for all records).

Thanks for your feedback

2024-02-29 15:38 UTC, thijsmie approved these changes

2024-03-01 07:42 UTC, thijsmie commented
I'll merge this as soon as the pipeline passes, seems you forgot to run the ruff formatter after your last change 😃

2024-03-01 10:23 UTC, matthieuEv commented
My Bad, totally forgot 🫠. This time it will work!

2024-03-03 10:06 UTC, thijsmie commented
Thank you @matthieuEv! In the future your PRs should automatically run the checks without me needing to approve them, allowing you to iterate a bit faster. I've also added a `ci.bash` script which you can run locally so you can test before pushing. I've just updated a test on your branch and rebased it on main to solve the merge conflict.

2024-03-03 10:06 UTC, merged

2024-03-03 10:21 UTC, matthieuEv commented
That sounds perfect to me. I'll be sure to use the bash script for local testing, it will help a lot, thanks!